[package]
name = "benihora"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
corus-v2 = { path = "../v2" }
perlin-noise = { path = "../perlin-noise" }
